### ISSUE TITLE
Typo usernames = accidental registrations. 

### ISSUE THREAD

**Issue by joshchernoff** [firestormforum/firestorm#96]
If I pass a false username by mistake wont that cause bad registrations? 

https://github.com/dailydrip/firestorm/blob/22e1dfa3c7107bb5cb6a7f5cfc2a8fb641065301/lib/firestorm_web/forums/forums.ex#L491-L494

**Comment by knewter** [comment]
Yes it is terrible and hilariously bad right now. That's on the list to deal with when fixing ACL stuff, i.e. very soon. Think of the email support itself as a horrible prototype for now.

**Comment by digitalcake** [comment]
No worries, I was just enjoying your dailydrip. That lead me to see how you deal with uberauth
